language: node_js

node_js:
  - "node"

sudo: required
dist: bionic

group: edge

branches:
  except:
    - release

before_script:
  - npm install

script:
  - npm run coverage

after_success:
  - npm run report